backend:
  name: github
  repo: chevrefeuille/bon-tabio

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes"
    extension: yml
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: string }
      - { label: "Image", name: "image", widget: image }
      - label: "Amount"
        name: amount
        widget: "object"
        fields:
        - {label: "Quantity", name: "quantity", widget: number }
        - {label: "Unit", name: "unit", widget: "string" }
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        fields:
        - {label: Name, name: "name", widget: string, default }
        - {label: Quantity, name: "quantity", widget: number }
        - {label: Unit, name: "unit", widget: string }
      - label: "Steps"
        name: "steps"
        widget: "list"
        fields:
        - {label: Name, name: "name", widget: string, default }
        - {label: Action, name: "action", widget: markdown }

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    extension: yml
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: string }
      - { label: "Date", name: "date", widget: date }
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
        - {label: Content, name: "content", widget: markdown }
        - {label: Image, name: "image", widget: image }
