backend:
  name: github
  repo: chevrefeuille/bon-tabio

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - label: "Amount"
        name: amount
        widget: "object"
        fields:
        - {label: "Quantity", name: "quantity", widget: "string" }
        - {label: "Unit", name: "unit", widget: "number "}
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        fields:
        - {label: Name, name: "name", widget: string, default }
        - {label: Quantity, name: "quantity", widget: number }
        - {label: Unit, name: "unit", widget: string }
      - label: "Steps"
        name: "steps"
        widget: "list"
        fields:
        - {label: Name, name: "name", widget: string, default }
        - {label: Action, name: "action", widget: markdown }
